colorscheme solarized-dark

set-option global tabstop 4
set-option global indentwidth 4
set-option global autoreload yes 
set-option -add global ui_options terminal_assitant=none

# Load options

source "%val{config}/mappings.kak"

