[font]
normal = { family = "Sarasa Fixed CL", style = "Regular" }
size = 13.0

[terminal.shell]
program = "pwsh.exe"
args = ["-NoLogo", "-wd ~"]

[[keyboard.bindings]]
key = "F11"
mods = "Super"
action = "ToggleFullscreen"
